config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "lists#index"
  resources :lists do
    resources :items, except: [:index, :show] do
      put :sort, on: :member
    end
  end
  resources :tags, only: [:index, :show] do
    get :search, on: :collection
  end
  resources :users, only: [:index, :show]
  get :search, to: "searches#search"
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :items, dependent: :destroy

  validates :title, presence: true

  def self.ransackable_attributes(auth_object = nil)
    []
  end

  def self.ransortable_attributes(auth_object = nil)
    ["title", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["user"]
  end

  # application_controller.rb (def keyword_search) ：List, Item, Tagモデルのキーワード検索。params[:model]の値により条件分岐。
  def self.search_records(keyword)
    joins(items: [:tags]).where(
      "title LIKE? or concept LIKE? or rule LIKE? or items.item_name LIKE? or items.description LIKE? or tags.tag_name LIKE?",
      "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"
    )
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  def index
    @q = List.ransack(params[:q])
    @q.sorts = "updated_at DESC" if @q.sorts.empty?
    @lists = @q.result.includes(:user)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def show
    @q = @list.items.ransack(params[:q])
    @q.sorts = "row_order ASC" if @q.sorts.empty?
    @items = @q.result.with_attached_images.includes(:list, :tags)
  end

  def edit
    redirect_to root_path unless current_user.id == @list.user_id
  end

  def update
    if @list.update(list_params)
      redirect_to list_path(@list.id)
    else
      render :edit
    end
  end

  def destroy
    @list.destroy if current_user.id == @list.user_id
    redirect_to user_path(current_user.id)
  end

  private
  def list_params
    params.require(:list).permit(:title, :concept, :rule).merge(user_id: current_user.id)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<%= form_with model: @list, local: true do |f| %>
  <div class="field title_field">
    <%= f.label :title, "●リストタイトル ［必須］" %>
    <%= f.text_field :title, autofocus: true %>
  </div>

  <div class="field concept_field">
    <%= f.label :concept, "●コンセプト ［任意］" %>
    <%= f.text_area :concept %>
  </div>

  <div class="field rule_field">
    <%= f.label :rule, "●リスト作成ルール ［任意］" %>
    <%= f.text_area :rule, placeholder: "タグのスコア1~5それぞれの段階・程度を表す言葉や代表例などの記載を推奨。" %>
  </div>

  <div class="actions">
    <%= f.submit "送信" %>
  </div>
<% end %>

app/views/lists/edit.html.erb
<div class="section edit_list_heading_section">
  <h2><%= "リスト編集：#{@list.title}" %></h2>
  <div class="link_bar">
    <%= link_to "リストへ戻る", list_path(@list.id) %>
  </div>
</div>

<div class="section edit_list_form_section">
  <%= render "form" %>
</div>

app/views/lists/index.html.erb
<h1 class="site_title">Five Level Tagging 【5段階タグ付けアプリ】</h1>

<div class="section lists_heading_section">
  <h2>リスト一覧（トップページ）</h2>
</div>

<div class="section lists_section">
  <h4>●全ユーザーが投稿したリスト一覧</h4>
  <div class="link_bar">
    <%= link_to "リスト新規投稿（ログイン中のみ可）", new_list_path %>
    <%= "投稿総数：#{@lists.length}" %>
    <span class="note">※列の見出しリンクをクリックして並び替え。</span>
  </div>

  <%= render "shared/list_table" %>
</div>

<div class="section message_for_testers">
  <h4>●テスト用アカウントにログインして閲覧する皆様へ</h4>
  <p class="note">
    ※既存データ（サンプルデータ）の編集・削除はご遠慮ください。（user1~2, list1~6, item1~72）<br>
    ※新規データの投稿・編集・削除は問題ございません。（データベースリセットの目安：平日22時頃）<br>
    ※開発中アプリにつき、レイアウト装飾（配色・フォントなど）は、一通りの機能実装後に着手します。
  </p>
</div>

app/views/lists/new.html.erb
<div class="section new_list_heading_section">
  <h2>リスト新規投稿</h2>
</div>

<div class="section new_list_form_section">
  <%= render "form" %>
</div>

app/views/lists/show.html.erb
<div class="section list_heading_section">
  <h2><%= "リスト：#{@list.title}" %></h2>
  <div class="link_bar">
    <% if user_signed_in? && current_user.id == @list.user_id %>
        <%= link_to "リスト編集", edit_list_path(@list.id) %>
        <%= link_to "リスト削除", list_path(@list.id), method: :delete, data: { confirm: "このリストを削除してもよろしいですか？\nリスト内のアイテムも全て削除されます。" } %>
    <% end %>
    <span><%= "作者名：" %><%= link_to @list.user.user_name, user_path(@list.user_id) %></span>
  </div>
</div>

<%# app/helpers/application_helper.rb(safe_linebreak) ：レコードカラム内の改行を、HTML上で安全に表示させる。 %>
<div class="section list_concept_section">
  <h4>●コンセプト</h4>
  <div class="text_box js_show_more_text">
    <div class="show_more_gradation"></div>
    <div class="show_more_button"></div>
    <div class="show_more_content"><%= safe_linebreak(@list.concept) %></div>
  </div>
</div>

<div class="section list_rule_section">
  <h4>●リスト作成ルール</h4>
  <div class="text_box js_show_more_text">
    <div class="show_more_gradation"></div>
    <div class="show_more_button"></div>
    <div class="show_more_content"><%= safe_linebreak(@list.rule) %></div>
  </div>
</div>

<div class="section list_items_section">
  <h4>●アイテム（リスト内項目）一覧</h4>
  <p class="note">
    ※画像を原寸大サイズで表示：画像を右クリック→「新しいタブで画像を開く」をクリック。<br>
    ※指定したタグのスコア順にアイテムを並び替え：タグ名をクリック。<br>
    ※リスト作者のみ、アイテムの順番を自由に指定・保存：「並び替え（作者指定順） ▲」の状態で、アイテム名または番号の部分をドラッグ＆ドロップ。
  </p>

  <div class="link_bar">
    <% if user_signed_in? && current_user.id == @list.user_id %>
      <%= link_to "アイテム新規投稿", new_list_item_path(list_id: @list.id), id: "js_link_new_item" %>
    <% end %>
    <%= "投稿総数：#{@items.length}" %>
    <%= sort_link(@q, :row_order, "並び替え（作者指定順）") %>
    <%= sort_link(@q, :item_name, "並び替え（アイテム名）") %>
    <%= sort_link(@q, :updated_at, "並び替え（アイテム更新日時）") %>
  </div>

  <%= render "shared/item_table" %>
</div>