config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "lists#index"
  resources :lists do
    resources :items, except: [:index, :show] do
      put :sort, on: :member
    end
  end
  resources :tags, only: [:index, :show] do
    get :search, on: :collection
  end
  resources :users, only: [:index, :show]
  get :search, to: "searches#search"
end

app/views/shared/_header.html.erb
<header class="global_nav">
  <div class="link_bar">
    <%= link_to "リスト一覧", lists_path %>
    <%= link_to "キーワード検索", search_path %>
    <%= link_to "タグ検索", tags_path %>
    <%= link_to "ユーザー一覧", users_path %>
    <% if user_signed_in? %>
      <%= link_to "マイページ", user_path(current_user.id) %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "ユーザー登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
    <% end %>
  </div>
</header>

app/views/shared/_item_table.html.erb
<%# ※外側の div(class="item_tables") ：tableタグ1つにつき、アイテムを1つ表示。
※内側の table(class="item_each_table") ：アイテム1つにつき、2行の表を表示。
→ sort_link ：クリックするたび、2行ずつの表(アイテム1つずつ)を丸ごと並び替えられる。 %>
<div class="item_tables" id="js_item_tables">
  <% @items.each_with_index do |item, i| %>
    <% if @list.present? %>
      <table class="item_each_table" id=<%= "item_table#{i+1}_id#{item.id}" %> href="<%= sort_list_item_path(list_id: item.list_id, id: item.id) %>">
    <% else %>
      <table class="item_each_table" id=<%= "item_table#{i+1}_id#{item.id}" %>>
    <% end %>
        <tbody>
          <tr>
            <td class="item_data_td">
              <div class="link_bar">
                <span class="item_updated_at_td"><%= item.updated_at.to_s(:datetime_jp) %></span>
                <% if user_signed_in? && current_user.id == item.list.user_id %>
                  <%= link_to "編集", edit_list_item_path(list_id: item.list_id, id: item.id) %>
                  <%= link_to "削除", list_item_path(list_id: item.list_id, id: item.id), method: :delete, data: { confirm: "このアイテムを削除してもよろしいですか？" } %>
                <% end %>
              </div>
              <% if @list.present? %>
                <span class="item_row_order_td js_handle"><%= "#{item.row_order}:" %></span>
              <% else %>
                <div class="item_list_td"><%= link_to item.list.title, list_path(item.list_id) %></div>
              <% end %>
              <span class="item_name_td js_handle"><%= item.item_name %></span>
            </td>

            <%# app/helpers/application_helper.rb(safe_linebreak) ：レコードカラム内の改行を、HTML上で安全に表示させる。 %>
            <td class="item_description_td js_show_more_item" colspan="2">
              <div class="show_more_gradation"></div>
              <div class="show_more_button"></div>
              <div class="show_more_content"><%= safe_linebreak(item.description) %></div>
            </td>

            <td class="item_image_td js_show_more_item">
              <div class="show_more_gradation"></div>
              <div class="show_more_button"></div>
              <div class="show_more_content">
                <div class="item_image_grid">
                  <% if item.images.attached? %>
                    <% item.images.each do |image| %>
                      <%= image_tag image, class: "item_image" %>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </td>
          </tr>

          <tr>
            <% Max::TAGS_IN_ROW.times do |i| %>
              <td class="item_tag_td">
                <% if @list.present? %>
                  <%= link_to item.tags[i].tag_name, tag_path(item.tags[i].id, list_id: item.list_id) if item.tags[i].present? %>
                <% else %>
                  <%= link_to item.tags[i].tag_name, tag_path(item.tags[i].id) if item.tags[i].present? %>
                <% end %>
                <%= "：#{item.item_tags[i].score}" if item.item_tags[i]&.score.present? %>
              </td>
            <% end %>
          </tr>
        </tbody>
      </table>
  <% end %>
</div>

app/views/shared/_list_table.html.erb
<table class="list_table">
  <thead>
    <tr>
      <th class="list_title_th"><%= sort_link(@q, :title, "リストタイトル") %></th>
      <th class="list_concept_th">コンセプト</th>
      <% if @user.blank? %>
        <th class="user_name_th"><%= sort_link(@q, :user_user_name, "作者名") %></th>
      <% end %>
      <th class="list_updated_at_th"><%= sort_link(@q, :updated_at, "リスト更新日時") %></th>
    </tr>
  </thead>

  <%# app/helpers/application_helper.rb(safe_linebreak) ：レコードカラム内の改行を、HTML上で安全に表示させる。 %>
  <%# config/application.rb(time_zone), config/initializers/time_formats.rb(:datetime_jp) ：更新日時のJST表示(並び替え用) %>
  <tbody>
    <% @lists.each_with_index do |list, i| %>
      <tr id=<%= "list_tr#{i+1}_id#{list.id}" %>>
        <td class="list_title_td"><%= link_to list.title, list_path(list.id) %></td>
        <td class="list_concept_td js_show_more_list">
          <div class="show_more_gradation"></div>
          <div class="show_more_button"></div>
          <div class="show_more_content"><%= safe_linebreak(list.concept) %></div>
        </td>
        <% if @user.blank? %>
          <td class="user_name_td"><%= link_to list.user.user_name, user_path(list.user_id) %></td>
        <% end %>
        <td class="list_updated_at_td"><%= list.updated_at.to_s(:datetime_jp) %></td>
      </tr>
    <% end %>
  </tbody>
</table>