config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  root to: "lists#index"
  resources :lists do
    resources :items, except: [:index, :show] do
      put :sort, on: :member
    end
  end
  resources :tags, only: [:index, :show] do
    get :search, on: :collection
  end
  resources :users, only: [:index, :show]
  get :search, to: "searches#search"
end

app/models/item.rb
class Item < ApplicationRecord
  has_many_attached :images

  belongs_to :list, touch: true

  has_many :item_tags, dependent: :destroy
  has_many :tags, through: :item_tags

  include RankedModel
  ranks :row_order, with_same: :list_id

  def self.ransackable_attributes(auth_object = nil)
    []
  end

  def self.ransortable_attributes(auth_object = nil)
    ["item_name", "updated_at", "row_order"]
  end

  def self.ransackable_associations(auth_object = nil)
    []
  end

  # application_controller.rb (def keyword_search) ：List, Item, Tagモデルのキーワード検索。params[:model]の値により条件分岐。
  def self.search_records(keyword)
    joins(:tags).where(
      "item_name LIKE? or description LIKE? or tags.tag_name LIKE?",
      "%#{keyword}%", "%#{keyword}%", "%#{keyword}%"
    )
  end

  # tags/show.html.erb (sort_link(@q, :item_tag_score, "並び替え（タグスコア）")) ：1つのタグに紐づくスコアで、アイテムを並び替え。
  scope :sort_by_item_tag_score_asc, -> { order("item_tags.score ASC") }
  scope :sort_by_item_tag_score_desc, -> { order("item_tags.score DESC") }
end

app/models/item_form.rb
class ItemForm
  include ActiveModel::Model

  attr_accessor(
    :id, :created_at, :updated_at,
    :item_name, :description, :row_order, :list_id,
    :images,
    :tag_names, :tag_name,
    :scores, :score, :item_id, :tag_id
  )

  validates :item_name, presence: true
  validates :images, length: { maximum: Max::IMAGES_PER_ITEM }
  validates :tag_names, :scores, length: { maximum: Max::TAGS_PER_ITEM }
  validates :tag_name, length: { maximum: 25 }
  validates :score, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }, allow_blank: true

  def save_item_form
    item = Item.create(item_name: item_name, description: description, list_id: list_id, images: images)
    Max::TAGS_PER_ITEM.times do |i|
      if tag_names[i].present?
        tag = Tag.where(tag_name: tag_names[i]).first_or_create
        Item.no_touching do
          ItemTag.create(item_id: item.id, tag_id: tag.id, score: scores[i])
        end
      end
    end
  end

  def update_item_form(params, item)
    item_tags = item.item_tags
    tag_names = params.delete(:tag_names)
    scores = params.delete(:scores)
    item.update(params)

    Max::TAGS_PER_ITEM.times do |i|
      if tag_names[i].present?
        tag = Tag.where(tag_name: tag_names[i]).first_or_create
        if item_tags[i].present?
          item_tags[i].update(item_id: item.id, tag_id: tag.id, score: scores[i])
        else
          ItemTag.create(item_id: item.id, tag_id: tag.id, score: scores[i])
        end
      elsif item_tags[i].present?
        item_tags[i].destroy
      end
    end
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list
  before_action :set_item, only: [:edit, :update, :destroy, :sort]

  def new
    @item_form = ItemForm.new
  end

  def create
    @item_form = ItemForm.new(item_form_params)
    if @item_form.valid?
      @item_form.save_item_form
      renumber_row_order(@list)
      redirect_to list_path(@list.id)
    else
      render :new
    end
  end

  def edit
    redirect_to list_path(@list.id) unless current_user.id == @list.user_id
    @item_form = ItemForm.new(@item.attributes)
    @item_form.tag_names = @item.tags.pluck(:tag_name)
    @item_form.scores = @item.item_tags.pluck(:score)
  end

  def update
    @item_form = ItemForm.new(item_form_params)
    if @item_form.valid?
      @item_form.update_item_form(item_form_params, @item)
      redirect_to list_path(@list.id)
    else
      render :edit
    end
  end

  def destroy
    @item.destroy if current_user.id == @list.user_id
    redirect_to list_path(@list.id)
  end

  def sort
    if current_user.id == @list.user_id
      @item.assign_attributes(sort_params)
      @item.save(touch: false)
      2.times { renumber_row_order(@list) }
    end
  end

  private
  def item_form_params
    params.require(:item_form).permit(:item_name, :description, images: [], tag_names: [], scores: []).merge(list_id: params[:list_id])
  end

  def sort_params
    params.require(:item).permit(:row_order_position)
  end

  def renumber_row_order(list)
    List.no_touching do
      list.items.rank(:row_order).each_with_index do |item, i|
        item.assign_attributes(row_order: i+1)
        item.save(touch: false)
      end
    end
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with model: @item_form, url: url, method: method, local: true, id: "js_item_form" do |f| %>
  <div class="field item_name_field">
    <%= f.label :item_name, "●アイテム名 ［必須］" %>
    <%= f.text_field :item_name, autofocus: true %>
  </div>

  <div class="field description_field">
    <%= f.label :description, "●説明 ［任意］" %>
    <%= f.text_area :description %>
  </div>

  <%# 画像ファイル選択ボタンを複数実装(multipleは不使用) ：別ディレクトリから選択可。ファイル名を別個に表示可。 %>
  <div class="field images_field">
    <%= f.label :images, "●画像（最大#{Max::IMAGES_PER_ITEM}枚） ［任意］", for: "item_form_image1" %>
    <% Max::IMAGES_PER_ITEM.times do |i| %>
      <%= f.file_field :images, name: "item_form[images][]", id: "item_form_image#{i+1}" %>
    <% end %>
  </div>

  <% Max::TAGS_PER_ITEM.times do |i| %>
    <div class="field tag_name_score_field">
      <%= f.label :tag_name, "●タグ名(#{i+1}) ［任意］", for: "item_form_tag_name#{i+1}" %>
      <% if @item.present? %>
        <%= f.text_field :tag_name, name: "item_form[tag_names][]", value: @item_form.tag_names[i], maxlength: "25", placeholder: "25文字以内", id: "item_form_tag_name#{i+1}" %>
      <% else %>
        <%= f.text_field :tag_name, name: "item_form[tag_names][]", maxlength: "25", placeholder: "25文字以内", id: "item_form_tag_name#{i+1}" %>
      <% end %>
      <div class="tag_search_results" id=<%= "tag_results_group#{i+1}" %>></div>

      <div class="score_field">
        <%= f.label :score, "●スコア(#{i+1}) ［任意］", for: "item_form_score#{i+1}" %>
        <% if @item.present? %>
          <%= f.number_field :score, name: "item_form[scores][]", value: @item_form.scores[i], min: 1, max: 5, class: "score_input", id: "item_form_score#{i+1}" %>
        <% else %>
          <%= f.number_field :score, name: "item_form[scores][]", min: 1, max: 5, class: "score_input", id: "item_form_score#{i+1}" %>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit '送信' %>
  </div>
<% end %>

app/views/items/edit.html.erb
<div class="section edit_item_heading_section">
  <h2><%= "アイテム編集：#{@item.item_name}" %></h2>
  <div class="link_bar">
    <%= link_to "リストへ戻る：#{@list.title}", list_path(@list.id) %>
  </div>
</div>

<div class="section edit_item_form_section">
  <%= render partial: "form", locals: { url: list_item_path(list_id: @list.id, id: @item.id), method: :patch } %>
</div>

app/views/items/new.html.erb
<div class="section new_item_heading_section">
  <h2>アイテム（リスト内項目）新規投稿</h2>
  <div class="link_bar">
    <%= link_to "リストへ戻る：#{@list.title}", list_path(@list.id) %>
  </div>
</div>

<div class="section new_item_form_section">
  <%= render partial: "form", locals: { url: list_items_path(list_id: @list.id), method: :post } %>
</div>